# Generated by Django 6.0.2 on 2026-02-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('failed_attempts', models.PositiveIntegerField(default=1)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Неудачная попытка входа',
                'verbose_name_plural': 'Неудачные попытки входа',
                'ordering': ['-last_attempt'],
            },
        ),
    ]
