# Generated by Django 6.0.2 on 2026-03-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_address_name_address_address_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Частный дом')], default='apartment', max_length=20, verbose_name='Тип адреса'),
        ),
        migrations.AddField(
            model_name='address',
            name='house_type',
            field=models.CharField(blank=True, help_text='Например: кирпичный, деревянный', max_length=50, verbose_name='Тип дома'),
        ),
        migrations.AddField(
            model_name='address',
            name='plot_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер участка'),
        ),
    ]
