# Generated by Django 6.0.2 on 2026-03-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_address_address_type_address_house_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='house_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='plot_number',
        ),
    ]
